#!/bin/bash

nextflow="./nextflow"
pyigmapArgs=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -help)
            shift
            ;;
        *)
            pyigmapArgs+=("$1")
            ;;
    esac
    shift
done

if [[ ! -f "$nextflow" ]]; then
    echo "Error: ./nextflow binary not found."
    exit 1
fi

if [[ ${#pyigmapArgs[@]} -eq 0 ]]; then
    echo "Error: pyigmap args are not specified."
    exit 1
fi

${nextflow} run main.nf "${pyigmapArgs[@]}"
exit $?